### ISSUE TITLE
Deleting lists prevents making a new list

### ISSUE THREAD

**Issue by justgage** [devrieda/react-editor#2]
Creating a list item and then deleting it makes to so that you can't create another list in that exact place.

Steps:
1. type `- asdf` and push enter and new list item will be created
2. push backspace till it's deleted
3. type `- asdf` and push enter and it will just create a dash without making a new list

**Comment by devrieda** [comment]
fixed with 56c987d9f69d09bf6e15aa00e3db7d5f6743081e
